import type { ApiClient } from '../client'

export interface ReadonlyUser { id: number; username: string; display_name: string; quota: number; used_quota: number; status: number; created_at: number; last_login_at: number }
export interface ReadonlyLog { id: number; user_id: number; created_at: string; type: number; username: string; model_name: string; channel_id: number; channel?: number; channel_name?: string; token_id?: number; token_name: string; prompt_tokens: number; completion_tokens: number; quota: number; use_time: number; request_id: string; upstream_request_id: string; content?: string; content_summary: string; group: string; ip: string; is_stream?: boolean | number | string; fallback?: boolean; fallback_checked?: boolean; fallback_channels?: string[]; other: string }
export interface ReadonlyLogSummary { quota: number; rpm: number; tpm: number }
export interface ReadonlyResponse<T> { items: T[]; configured: boolean; total: number; page?: number; page_size?: number; has_more?: boolean; next_cursor?: string; previous_cursor?: string; summary?: ReadonlyLogSummary }
export interface ReadonlyLogStatResponse { configured: boolean; summary: ReadonlyLogSummary }
export interface ReadonlyLogCountResponse { configured: boolean; total: number }
const query = (params: Record<string, string | number | undefined>) => { const out = new URLSearchParams(); Object.entries(params).forEach(([key, value]) => { if (value !== undefined && value !== '') out.set(key, String(value)) }); const text = out.toString(); return text ? `?${text}` : '' }
// 日志页支持取消已过期请求，切换筛选时不让旧 fetch 继续占用只读连接。
const requestOptions = (signal?: AbortSignal): RequestInit | undefined => signal ? { signal } : undefined
export const passthroughApi = (client: ApiClient) => ({
  users: (params: { site?: string; user_ids?: string; keyword?: string; status?: number; limit?: number; offset?: number }) => client.request<ReadonlyResponse<ReadonlyUser>>(`/api/dashboard/passthrough/users${query(params)}`),
  logs: (params: { site?: string; user_ids?: string; username?: string; group?: string; start_time?: string; end_time?: string; token_name?: string; model_name?: string; request_id?: string; upstream_request_id?: string; channel_id?: number; channel?: number; log_type?: number; type?: number; limit?: number; offset?: number; cursor?: string; p?: number; page_size?: number }, signal?: AbortSignal) => client.request<ReadonlyResponse<ReadonlyLog>>(`/api/dashboard/passthrough/logs${query(params)}`, requestOptions(signal)),
  logStat: (params: { site?: string; user_ids?: string; username?: string; group?: string; start_time?: string; end_time?: string; token_name?: string; model_name?: string; request_id?: string; upstream_request_id?: string; channel_id?: number; channel?: number; log_type?: number; type?: number }, signal?: AbortSignal) => client.request<ReadonlyLogStatResponse>(`/api/dashboard/passthrough/logs/stat${query(params)}`, requestOptions(signal)),
  logCount: (params: { site?: string; user_ids?: string; username?: string; group?: string; start_time?: string; end_time?: string; token_name?: string; model_name?: string; request_id?: string; upstream_request_id?: string; channel_id?: number; channel?: number; log_type?: number; type?: number; p?: number; page_size?: number }, signal?: AbortSignal) => client.request<ReadonlyLogCountResponse>(`/api/dashboard/passthrough/logs/count${query(params)}`, requestOptions(signal)),
})
