<script setup lang="ts">
import { computed, ref } from 'vue'
const props=withDefaults(defineProps<{items:any[];selectedKey:string;channelMode?:boolean}>(),{channelMode:false});const emit=defineEmits<{'update:selectedKey':[value:string]}>();const search=ref('');const active=ref<string[]>([]);const collapsed=ref({idle:true,disabled:true});const view=ref<'list'|'wall'>((localStorage.getItem('ct-channel-view') as 'list'|'wall')||'list')
const channelMode=computed(()=>props.channelMode||props.items.some(item=>item.status!==undefined))
const kind=(item:any)=>item.status&&item.status!=='enabled'?'disabled':item.request_count===0?'idle':(item.error_rate||0)>=.1?'danger':(item.error_rate||0)>0?'warning':'normal'
const labels:{[key:string]:string}={danger:'异常',warning:'注意',normal:'正常',idle:'无流量',disabled:'已禁用'}
const searched=computed(()=>props.items.filter(item=>`${item.display_key} ${item.dimension_key}`.toLowerCase().includes(search.value.toLowerCase())))
const counts=computed(()=>Object.fromEntries(Object.keys(labels).map(key=>[key,searched.value.filter(item=>kind(item)===key).length])))
const visible=computed(()=>searched.value.filter(item=>active.value.length?active.value.includes(kind(item)):!['idle','disabled'].includes(kind(item))).sort((a,b)=>{const weight:any={danger:0,warning:1,normal:2};return (weight[kind(a)]??3)-(weight[kind(b)]??3)||b.request_count-a.request_count}))
const folded=(key:string)=>searched.value.filter(item=>kind(item)===key)
function toggle(key:string){active.value=active.value.includes(key)?active.value.filter(x=>x!==key):[...active.value,key]}
function setView(value:'list'|'wall'){view.value=value;localStorage.setItem('ct-channel-view',value)}
</script>
<template><div class="dimension-workspace"><aside class="dimension-list"><el-input v-model="search" clearable placeholder="搜索名称或 ID"/><div class="dimension-filters"><el-tag v-for="(label,key) in labels" v-show="channelMode||key!=='disabled'" :key="key" :type="key==='danger'?'danger':key==='warning'?'warning':key==='normal'?'success':'info'" :effect="active.includes(String(key))?'dark':'plain'" @click="toggle(String(key))">{{label}} {{counts[key]||0}}</el-tag></div><div v-if="channelMode" class="dimension-view-toggle"><el-button size="small" :type="view==='list'?'primary':''" @click="setView('list')">列表</el-button><el-button size="small" :type="view==='wall'?'primary':''" @click="setView('wall')">健康墙</el-button></div><div class="dimension-count">共 {{searched.length}} 项</div><div v-if="channelMode&&view==='wall'" class="health-wall"><button v-for="item in searched" :key="item.dimension_key" :class="['health-tile',kind(item),{active:item.dimension_key===selectedKey}]" @click="emit('update:selectedKey',item.dimension_key)"><strong>{{item.display_key}}</strong><span>{{((item.error_rate||0)*100).toFixed(1)}}% · {{item.request_count}} 请求</span></button></div><template v-else><button v-for="item in visible" :key="item.dimension_key" :class="{active:item.dimension_key===selectedKey}" @click="emit('update:selectedKey',item.dimension_key)"><slot name="row" :item="item"/></button><section v-for="key in channelMode?['idle','disabled']:['idle']" :key="key" class="folded-group"><button class="folded-title" @click="collapsed[key as 'idle'|'disabled']=!collapsed[key as 'idle'|'disabled']">{{labels[key]}}（{{folded(key).length}}） {{collapsed[key as 'idle'|'disabled']?'展开':'收起'}}</button><template v-if="!collapsed[key as 'idle'|'disabled']"><button v-for="item in folded(key)" :key="item.dimension_key" :class="{active:item.dimension_key===selectedKey}" @click="emit('update:selectedKey',item.dimension_key)"><slot name="row" :item="item"/></button></template></section></template></aside><section class="dimension-detail"><slot v-if="selectedKey" name="detail"/><el-empty v-else description="请选择一项查看详情"/></section></div></template>
