<script setup lang="ts">
import{computed,onBeforeUnmount,ref,watch}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import{dashboard}from'../api';
const props=defineProps<{site:string;from:string;to:string;label:string}>(),emit=defineEmits<{completed:[]}>();
type Task=Awaited<ReturnType<typeof dashboard.reportTasks>>['items'][number];
const tasks=ref<Task[]>([]),create=ref(false),history=ref(false),opened=ref(false),selected=ref(''),submitting=ref(false),overwrite=ref(false),error=ref('');let timer:ReturnType<typeof setTimeout>|undefined;let revision=0;let disposed=false;
const active=computed(()=>tasks.value.find(t=>['pending','running'].includes(t.status))),latest=computed(()=>active.value||tasks.value[0]),current=computed(()=>tasks.value.find(t=>t.id===selected.value));
const status=(s:string)=>({pending:'等待生成',running:'正在生成',complete:'生成成功',failed:'部分生成失败',cancelled:'已取消',reused:'复用已有',}[s]||s);
const done=(t:Task)=>t.days.filter(d=>!['pending','running'].includes(d.status)).length;
const percent=(t:Task)=>t.days.length?Math.min(['pending','running'].includes(t.status)?99:100,Math.floor(done(t)/t.days.length*100)):0;
const count=(t:Task,s:string)=>t.days.filter(d=>d.status===s).length;
const processed=(t:Task)=>t.days.reduce((n,d)=>n+d.processed,0).toLocaleString();
const range=(t:Task)=>`${t.from} 至 ${new Date(new Date(t.to+'T00:00:00+08:00').getTime()-86400000).toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'})}`;
const messages:Record<string,string>={report_task_busy:'已有报表任务正在进行，请等待完成',report_no_closed_days:'所选日期尚未结束，暂不能生成正式报表',report_create_failed:'创建任务失败，请重试',report_cancel_failed:'取消失败，请刷新状态后重试',report_source_read_failed:'读取订单失败，重试后仍未成功',billing_money_snapshot_unavailable:'读取站点计费设置失败',report_user_price_invalid:'请求计费数据无效',billing_currency_unavailable:'站点币种配置无效'};
const message=(e:unknown)=>{const code=(e as {code?:string})?.code;return code&&messages[code]||'操作失败，请稍后重试'};
async function refresh(){const site=props.site,rev=revision;if(!site)return;try{const previous=new Map(tasks.value.map(t=>[t.id,t.status])),result=await dashboard.reportTasks(site);if(rev!==revision||disposed)return;tasks.value=result.items;error.value='';if(tasks.value.some(t=>!['pending','running'].includes(t.status)&&previous.get(t.id)!==t.status))emit('completed');}catch{if(rev===revision)error.value='任务状态读取失败，请重试';}}
function show(t:Task){selected.value=t.id;opened.value=true;}
function openCreate(){overwrite.value=false;create.value=true;}
async function generate(){submitting.value=true;try{const t=await dashboard.createReportTask({instance_id:props.site,from:props.from,to:props.to,overwrite:overwrite.value});create.value=false;await refresh();selected.value=t.id;opened.value=true;if(t.status==='complete')emit('completed');}catch(e){ElMessage.error(message(e));}finally{submitting.value=false;}}
async function cancel(t:Task){try{await ElMessageBox.confirm('取消后保留已完成的日报表。','取消生成任务',{type:'warning',confirmButtonText:'确定取消',cancelButtonText:'继续生成'});await dashboard.cancelReportTask(props.site,t.id);await refresh();emit('completed');}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(message(e));}}
watch(()=>props.site,()=>{revision++;tasks.value=[];opened.value=false;create.value=false;void refresh();},{immediate:true});
async function poll(){await refresh();if(!disposed)timer=setTimeout(poll,3000)}timer=setTimeout(poll,3000);onBeforeUnmount(()=>{disposed=true;clearTimeout(timer);});
</script>
<template><div class="report-actions"><el-button @click="history=true">生成记录</el-button><el-button type="primary" :disabled="!!active||!site||!!error" @click="openCreate">{{active?'任务进行中':'生成报表'}}</el-button></div>
<el-alert v-if="error" type="error" :closable="false" :title="error"><el-button link @click="refresh">重试</el-button></el-alert>
<div v-if="latest" class="report-progress"><span>{{range(latest)}}</span><b>{{status(latest.status)}}</b><span>已处理 {{done(latest)}} / {{latest.days.length}} 天</span><el-progress :percentage="percent(latest)" :status="latest.status==='complete'?'success':latest.status==='failed'?'exception':undefined" style="width:170px"/><el-button link type="primary" @click="show(latest)">{{active?'查看生成进度':'查看生成结果'}}</el-button><el-button v-if="active" link type="danger" @click="cancel(active)">取消任务</el-button></div>
<el-dialog v-model="create" title="生成报表" width="460px"><el-descriptions :column="1"><el-descriptions-item label="报表日期">{{label}}</el-descriptions-item></el-descriptions><el-checkbox v-model="overwrite">覆盖已有日报表</el-checkbox><p class="muted">{{overwrite?'重新计算所选日期，生成成功后替换原报表。':'只生成缺失日报表，已有报表直接复用。'}} 当月生成至昨天。</p><template #footer><el-button @click="create=false">取消</el-button><el-button type="primary" :loading="submitting" :disabled="!!active" @click="generate">开始生成</el-button></template></el-dialog>
<el-dialog v-model="opened" title="报表生成进度" width="min(1000px,95vw)"><template v-if="current"><div class="report-progress"><b>{{range(current)}} · {{status(current.status)}}</b><span>生成 {{count(current,'complete')}} 天 · 复用 {{count(current,'reused')}} 天 · 失败 {{count(current,'failed')}} 天</span><span>已处理 {{processed(current)}} 条请求</span><el-button v-if="['pending','running'].includes(current.status)" link type="danger" @click="cancel(current)">取消任务</el-button></div><el-progress :percentage="percent(current)"/><el-table :data="current.days" max-height="430" size="small"><el-table-column prop="day" label="日期" width="130"/><el-table-column label="状态" width="130"><template #default="s">{{status(s.row.status)}}</template></el-table-column><el-table-column prop="processed" label="已处理请求" width="120"/><el-table-column label="失败原因"><template #default="s">{{messages[s.row.error]||s.row.error||'—'}}</template></el-table-column></el-table></template></el-dialog>
<el-dialog v-model="history" title="报表生成记录 · 最近 100 个任务" width="min(1100px,95vw)"><el-table :data="tasks" max-height="550" empty-text="暂无生成记录"><el-table-column label="提交时间" width="180"><template #default="s">{{new Date(s.row.created_at).toLocaleString('zh-CN')}}</template></el-table-column><el-table-column label="报表区间" min-width="210"><template #default="s">{{range(s.row)}}</template></el-table-column><el-table-column label="方式" width="100"><template #default="s">{{s.row.automatic?'自动生成':s.row.overwrite?'手动覆盖':'补齐缺失'}}</template></el-table-column><el-table-column label="状态" width="125"><template #default="s">{{status(s.row.status)}}</template></el-table-column><el-table-column label="进度" width="100"><template #default="s">{{done(s.row)}} / {{s.row.days.length}} 天</template></el-table-column><el-table-column width="80"><template #default="s"><el-button link type="primary" @click="show(s.row)">详情</el-button></template></el-table-column></el-table></el-dialog>
</template><style scoped>.report-actions{display:flex;gap:8px;justify-content:flex-end;margin-bottom:10px}.report-progress{display:flex;align-items:center;flex-wrap:wrap;gap:16px;padding:12px 16px;border:1px solid var(--el-border-color-light);background:var(--el-color-primary-light-9);border-radius:7px;margin-bottom:12px;font-size:13px}.muted{font-size:12px;color:var(--el-text-color-secondary);line-height:1.8}</style>
