CREATE TABLE IF NOT EXISTS archive_day_versions (
  day_version_id BINARY(16) NOT NULL,
  log_date DATE NOT NULL,
  version_no INT UNSIGNED NOT NULL,
  previous_version_id BINARY(16) NULL,
  build_task_id BINARY(16) NOT NULL,
  state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  verified_mutation_revision BIGINT UNSIGNED NOT NULL,
  reconcile_run_id BINARY(16) NOT NULL,
  parser_version INT UNSIGNED NOT NULL,
  fact_schema_version INT UNSIGNED NOT NULL,
  evidence_codec_version INT UNSIGNED NOT NULL,
  storage_month CHAR(6) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  all_rows DECIMAL(38,0) NULL,
  consume_rows DECIMAL(38,0) NULL,
  consume_quota DECIMAL(38,0) NULL,
  raw_digest BINARY(32) NULL,
  facts_digest BINARY(32) NULL,
  manifest_json JSON NULL,
  manifest_hash BINARY(32) NULL,
  publish_revision BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL,
  published_at DATETIME(6) NULL,
  PRIMARY KEY (day_version_id),
  UNIQUE KEY uq_archive_day_version (log_date, version_no),
  UNIQUE KEY uq_archive_day_id (log_date, day_version_id),
  KEY idx_archive_version_build (state, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
