CREATE TABLE IF NOT EXISTS archive_reconcile_runs (
  run_id BINARY(16) NOT NULL,
  task_id BINARY(16) NOT NULL,
  attempt INT UNSIGNED NOT NULL,
  log_date DATE NOT NULL,
  method VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  state VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  phase VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  policy_json JSON NOT NULL,
  assurance_json JSON NOT NULL,
  schema_fingerprint BINARY(32) NOT NULL,
  start_revision BIGINT UNSIGNED NOT NULL,
  final_revision BIGINT UNSIGNED NULL,
  writer_epoch BIGINT UNSIGNED NOT NULL,
  progress_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
  scan_json JSON NOT NULL,
  summary_json JSON NOT NULL,
  issue_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  error_code VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin NULL,
  source_now_unix BIGINT NOT NULL DEFAULT 0,
  read_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  elapsed_millis BIGINT UNSIGNED NOT NULL DEFAULT 0,
  catalog_revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
  started_at DATETIME(6) NOT NULL,
  completed_at DATETIME(6) NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (run_id),
  UNIQUE KEY uq_archive_reconcile_task (task_id, attempt),
  KEY idx_archive_reconcile_date (log_date, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
