CREATE TABLE IF NOT EXISTS billing_facts_template (
  day_version_id BINARY(16) NOT NULL,
  source_log_id BIGINT NOT NULL,
  log_date DATE NOT NULL,
  created_unix BIGINT NOT NULL,
  log_type BIGINT NOT NULL,
  user_id BIGINT NULL,
  token_id BIGINT NULL,
  channel_id BIGINT NULL,
  username_snapshot VARCHAR(255) NULL,
  token_name_snapshot VARCHAR(255) NULL,
  model_name VARCHAR(255) NULL,
  group_name VARCHAR(255) NULL,
  request_id VARCHAR(255) NULL,
  upstream_request_id VARCHAR(255) NULL,
  quota BIGINT NULL,
  source_prompt_tokens BIGINT NULL,
  source_completion_tokens BIGINT NULL,
  input_tokens BIGINT NULL,
  output_tokens BIGINT NULL,
  cache_read_tokens BIGINT NULL,
  cache_write_tokens BIGINT NULL,
  cache_write_5m_tokens BIGINT NULL,
  cache_write_1h_tokens BIGINT NULL,
  image_input_tokens BIGINT NULL,
  image_output_tokens BIGINT NULL,
  audio_input_tokens BIGINT NULL,
  audio_output_tokens BIGINT NULL,
  pricing_snapshot_json JSON NOT NULL,
  usage_context_json JSON NOT NULL,
  evidence_hash BINARY(32) NOT NULL,
  raw_row_hash BINARY(32) NOT NULL,
  fact_hash BINARY(32) NOT NULL,
  fact_json JSON NOT NULL,
  parse_state VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  issue_codes_json JSON NOT NULL,
  PRIMARY KEY (day_version_id, source_log_id),
  KEY idx_archive_fact_order (day_version_id, created_unix, source_log_id),
  KEY idx_archive_fact_subject (user_id, log_date, day_version_id),
  KEY idx_archive_fact_token (token_id, log_date, day_version_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
