import { createApp } from 'vue'
import { createPinia } from 'pinia'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import App from './App.vue'
import { router } from './router'
import './styles.css'
import './b2.css'
import './b3.css'
import './b4.css'
import './b5.css'
import './b6.css'
import './b7.css'
createApp(App).use(createPinia()).use(router).use(ElementPlus).mount('#app')
