import { createApp } from 'vue'
import { createPinia } from 'pinia'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import 'element-plus/theme-chalk/dark/css-vars.css'
import App from './App.vue'
import { router } from './router'
import './styles.css'
import './b2.css'
import './b3.css'
import './b4.css'
import './b5.css'
import './b6.css'
import './b7.css'
import './b8.css'
import './b9.css'
import './design.css'
import './polish.css'
import './theme.css'
import './palettes.css'
import './fonts.css'
import './shell.css'
import './surfaces.css'
import { initializeTheme } from './composables/useTheme'
import './mobile.css'
import { mobileCards } from './utils/mobileCards'
initializeTheme()
createApp(App).directive('mobile-cards', mobileCards).use(createPinia()).use(router).use(ElementPlus).mount('#app')
