CREATE TABLE IF NOT EXISTS billing_request_details (
  job_id VARCHAR(40) NOT NULL,
  instance_id VARCHAR(64) NOT NULL,
  bill_day DATE NOT NULL,
  source_log_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL,
  request_id VARCHAR(128) NOT NULL DEFAULT '',
  user_id BIGINT NOT NULL,
  username VARCHAR(128) NOT NULL DEFAULT '',
  token_id BIGINT NOT NULL DEFAULT 0,
  token_name VARCHAR(128) NOT NULL DEFAULT '',
  channel_id BIGINT NOT NULL DEFAULT 0,
  channel_name VARCHAR(255) NOT NULL DEFAULT '',
  model_name VARCHAR(255) NOT NULL DEFAULT '',
  billing_mode VARCHAR(24) NOT NULL,
  prompt_tokens BIGINT NOT NULL DEFAULT 0,
  completion_tokens BIGINT NOT NULL DEFAULT 0,
  cache_read_tokens BIGINT NOT NULL DEFAULT 0,
  cache_write_tokens BIGINT NOT NULL DEFAULT 0,
  cache_write_5m_tokens BIGINT NOT NULL DEFAULT 0,
  cache_write_1h_tokens BIGINT NOT NULL DEFAULT 0,
  input_price DECIMAL(24,8) NOT NULL DEFAULT 0,
  output_price DECIMAL(24,8) NOT NULL DEFAULT 0,
  cache_read_price DECIMAL(24,8) NOT NULL DEFAULT 0,
  cache_write_price DECIMAL(24,8) NOT NULL DEFAULT 0,
  cache_write_5m_price DECIMAL(24,8) NOT NULL DEFAULT 0,
  cache_write_1h_price DECIMAL(24,8) NOT NULL DEFAULT 0,
  per_request_price DECIMAL(24,8) NOT NULL DEFAULT 0,
  input_amount DECIMAL(24,8) NOT NULL DEFAULT 0,
  output_amount DECIMAL(24,8) NOT NULL DEFAULT 0,
  cache_read_amount DECIMAL(24,8) NOT NULL DEFAULT 0,
  cache_write_amount DECIMAL(24,8) NOT NULL DEFAULT 0,
  cache_write_5m_amount DECIMAL(24,8) NOT NULL DEFAULT 0,
  cache_write_1h_amount DECIMAL(24,8) NOT NULL DEFAULT 0,
  total_amount DECIMAL(24,8) NOT NULL DEFAULT 0,
  calculated_quota BIGINT NOT NULL,
  logged_quota BIGINT NOT NULL,
  created_record_at DATETIME(6) NOT NULL,
  PRIMARY KEY (job_id, source_log_id),
  KEY idx_billing_request_user_day (instance_id, user_id, bill_day, created_at, source_log_id),
  KEY idx_billing_request_channel_day (instance_id, channel_id, bill_day)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS billing_user_daily_active (
  instance_id VARCHAR(64) NOT NULL,
  bill_day DATE NOT NULL,
  user_id BIGINT NOT NULL,
  job_id VARCHAR(40) NOT NULL,
  activated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (instance_id, bill_day, user_id),
  KEY idx_billing_user_daily_job (job_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS billing_user_daily_files (
  job_id VARCHAR(40) NOT NULL,
  instance_id VARCHAR(64) NOT NULL,
  bill_day DATE NOT NULL,
  user_id BIGINT NOT NULL,
  relative_path VARCHAR(512) NOT NULL,
  file_size BIGINT NOT NULL,
  sha256 CHAR(64) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (job_id, bill_day, user_id),
  KEY idx_billing_daily_file_lookup (instance_id, bill_day, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
