CREATE TABLE IF NOT EXISTS billing_compact_daily_totals (
  job_id VARCHAR(40) NOT NULL,
  instance_id VARCHAR(64) NOT NULL,
  bill_day DATE NOT NULL,
  user_id BIGINT NOT NULL,
  username VARCHAR(128) NOT NULL DEFAULT '',
  token_id BIGINT NOT NULL DEFAULT 0,
  token_name VARCHAR(128) NOT NULL DEFAULT '',
  channel_id BIGINT NOT NULL DEFAULT 0,
  channel_name VARCHAR(255) NOT NULL DEFAULT '',
  model_name VARCHAR(255) NOT NULL DEFAULT '',
  request_count BIGINT NOT NULL DEFAULT 0,
  prompt_tokens BIGINT NOT NULL DEFAULT 0,
  completion_tokens BIGINT NOT NULL DEFAULT 0,
  cache_read_tokens BIGINT NOT NULL DEFAULT 0,
  cache_write_tokens BIGINT NOT NULL DEFAULT 0,
  cache_write_5m_tokens BIGINT NOT NULL DEFAULT 0,
  cache_write_1h_tokens BIGINT NOT NULL DEFAULT 0,
  calculated_quota BIGINT NOT NULL DEFAULT 0,
  total_amount DECIMAL(30,12) NOT NULL DEFAULT 0,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (job_id,bill_day,user_id,token_id,channel_id,model_name),
  KEY idx_billing_compact_user_day (instance_id,user_id,bill_day),
  KEY idx_billing_compact_channel_day (instance_id,channel_id,bill_day)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
