CREATE TABLE IF NOT EXISTS billing_statement_reconciliation_orders (
  job_id VARCHAR(40) NOT NULL,
  source_log_id BIGINT NOT NULL,
  instance_id VARCHAR(64) NOT NULL,
  created_at DATETIME NOT NULL,
  request_id VARCHAR(255) NOT NULL DEFAULT '',
  upstream_request_id VARCHAR(255) NOT NULL DEFAULT '',
  user_id BIGINT NOT NULL DEFAULT 0,
  username VARCHAR(128) NOT NULL DEFAULT '',
  token_id BIGINT NOT NULL DEFAULT 0,
  token_name VARCHAR(128) NOT NULL DEFAULT '',
  channel_id BIGINT NOT NULL DEFAULT 0,
  channel_name VARCHAR(255) NOT NULL DEFAULT '',
  model_name VARCHAR(255) NOT NULL DEFAULT '',
  prompt_tokens BIGINT NOT NULL DEFAULT 0,
  completion_tokens BIGINT NOT NULL DEFAULT 0,
  cache_read_tokens BIGINT NOT NULL DEFAULT 0,
  cache_write_tokens BIGINT NOT NULL DEFAULT 0,
  calculated_quota BIGINT NOT NULL DEFAULT 0,
  logged_quota BIGINT NOT NULL DEFAULT 0,
  quota_difference BIGINT NOT NULL DEFAULT 0,
  calculated_amount DECIMAL(30,12) NOT NULL DEFAULT 0,
  logged_amount DECIMAL(30,12) NOT NULL DEFAULT 0,
  amount_difference DECIMAL(30,12) NOT NULL DEFAULT 0,
  reason VARCHAR(64) NOT NULL,
  detected_at DATETIME(6) NOT NULL,
  PRIMARY KEY (job_id, source_log_id),
  KEY idx_statement_reconciliation_job_time (job_id, created_at, source_log_id),
  CONSTRAINT fk_statement_reconciliation_job FOREIGN KEY (job_id) REFERENCES billing_jobs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
