ALTER TABLE operation_audits ADD COLUMN actor_type VARCHAR(24) NOT NULL DEFAULT 'unknown';
ALTER TABLE operation_audits ADD COLUMN actor_role VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE operation_audits ADD COLUMN source_component VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE operation_audits ADD COLUMN trigger_type VARCHAR(24) NOT NULL DEFAULT 'unknown';
ALTER TABLE operation_audits ADD COLUMN request_id VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE operation_audits ADD COLUMN correlation_id VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE operation_audits ADD COLUMN client_ip VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE operation_audits ADD COLUMN auth_method VARCHAR(24) NOT NULL DEFAULT '';
ALTER TABLE operation_audits ADD COLUMN http_method VARCHAR(12) NOT NULL DEFAULT '';
ALTER TABLE operation_audits ADD COLUMN route VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE operation_audits ADD COLUMN http_status SMALLINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE operation_audits ADD COLUMN error_summary VARCHAR(1000) NOT NULL DEFAULT '';
ALTER TABLE operation_audits ADD COLUMN updated_at DATETIME(6) NULL;
UPDATE operation_audits SET updated_at=created_at WHERE updated_at IS NULL;
ALTER TABLE operation_audits MODIFY COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
UPDATE operation_audits SET actor_type=CASE WHEN actor_id LIKE 'system:%' OR actor_id LIKE 'agent:%' THEN 'system' WHEN actor_id='token' THEN 'service_token' WHEN actor_id IN ('','unknown','legacy-admin') THEN 'unknown' ELSE 'human' END WHERE actor_type='unknown';
UPDATE operation_audits SET trigger_type=CASE WHEN actor_type='system' THEN 'automatic' ELSE 'manual' END WHERE trigger_type='unknown';
UPDATE operation_audits SET source_component=SUBSTRING_INDEX(operation_type,'.',1) WHERE source_component='';
CREATE INDEX idx_operation_audits_actor_created ON operation_audits (actor_id, created_at);
CREATE INDEX idx_operation_audits_correlation ON operation_audits (correlation_id, created_at);
