<script setup lang="ts">
import {computed,onBeforeUnmount,ref,watch} from 'vue';
import{ElMessage}from'element-plus';import type{BillingJob,ReadonlyUser}from'@ct/shared';
import AppShell from '../components/AppShell.vue';import BillingDailyDetails from '../components/BillingDailyDetails.vue';import BillingGenerationBatch from '../components/BillingGenerationBatch.vue';import BillingGenerationHistory from '../components/BillingGenerationHistory.vue';
import{dashboard,passthrough}from'../api';import{useFiltersStore}from'../stores/filters';import{startBillingFileDownload,billingTaskErrorMessage}from'../utils/httpError';
import BillingMonthlyPreview from '../components/BillingMonthlyPreview.vue';
import {billingWorkspaceRows,type BillingWorkspaceRow} from '../utils/billingWorkspace';
import {coverageLabel,coverageStatus,coverageTooltip} from '../utils/billingCoverage';
import {formatBillingDiscount} from '../utils/billingDiscount';
import BillingCatalog from '../components/BillingCatalog.vue';
const view=ref<'catalog'|'workspace'>('catalog');
const catalogView=ref<InstanceType<typeof BillingCatalog>>();
const monthlyView=ref<InstanceType<typeof BillingMonthlyPreview>>();
const detailView=ref<InstanceType<typeof BillingDailyDetails>>();
const batchView=ref<InstanceType<typeof BillingGenerationBatch>>();
const historyView=ref<InstanceType<typeof BillingGenerationHistory>>();
function openWorkspace(){view.value='workspace';if(!subjects.value.length)void searchSubjects();}
function onSubjectDropdown(visible:boolean){if(visible)void searchSubjects();}
function openCatalogBill(bill:Bill){
 const id=props.kind==='user'?bill.job.user_id:bill.job.upstream_id;
 if(!id||!bill.job.range_from)return;
 const name=(props.kind==='user'?bill.job.user_name:bill.job.upstream_name)||`${props.kind==='user'?'用户':'上游'} #${id}`;
 if(!subjects.value.some(v=>v.id===id))subjects.value.push({id,name});
 subjectRevision++;items.value=[];selected.value=id;month.value=day(bill.job.range_from).slice(0,7);tab.value=category(bill.job);view.value='workspace';
}
function downloadCatalogBill(bill:Bill){if(props.kind==='user'&&category(bill.job)==='daily')detailView.value?.open(bill.job,true);else download(bill);}
function onGenerated(value:string){month.value=value;void load();void catalogView.value?.refresh();}
function openHistory(){historyView.value?.open();}
const props=withDefaults(defineProps<{kind?:'user'|'upstream'}>(),{kind:'user'}),filters=useFiltersStore();
const currencyLabel=(v?:{type:string;symbol?:string})=>v?(v.type==='CUSTOM'?v.symbol||'自定义币种':v.type==='TOKENS'?'额度':v.type):'';
const generationBusy=ref(true),siteJobs=ref<BillingJob[]>([]);
const creationBlocked=computed(()=>generationBusy.value||!!batchView.value?.active||!!batchView.value?.saving);
let busyRevision=0;
async function checkGenerationBusy(){const n=++busyRevision;try{const r=await dashboard.billingGenerationStatus(filters.site_id,props.kind+'_statement');if(n===busyRevision){generationBusy.value=r.busy;siteJobs.value=r.jobs;batchView.value?.restore(r.targets);}}catch{if(n===busyRevision)generationBusy.value=true;}}
const remaining=ref(0),siteCurrency=ref('');
const currency=computed(()=>{const labels=[...new Set(visible.value.map(v=>currencyLabel(v.currency)).filter(Boolean))];return labels.length>1?'多币种':labels[0]||siteCurrency.value||'—';});
const selected=ref<number>(),subjects=ref<{id:number;name:string;role?:number}[]>([]),month=ref(new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'}).slice(0,7)),tab=ref('daily'),loading=ref(false),error=ref(''),history=ref(false),sample=ref(false),generate=ref(false),saving=ref(false),progress=ref(false);
const range=ref<[string,string]>(['','']),mode=ref<'fill'|'temporary'|'monthly'>('fill');
type Bill=Awaited<ReturnType<typeof dashboard.billingWorkspace>>['items'][number];const items=ref<Bill[]>([]),steps=ref<{step_no:number;status:string;processed_rows:number;range_from:string;range_to:string}[]>([]),activeJob=ref<BillingJob>();
let revision=0,subjectRevision=0,poll:ReturnType<typeof setInterval>|undefined;
const period=computed(()=>{const from=`${month.value}-01T00:00:00+08:00`;const [y,m]=month.value.split('-').map(Number);const next=m===12?`${y+1}-01`:`${y}-${String(m+1).padStart(2,'0')}`;return{from,to:`${next}-01T00:00:00+08:00`};});
const local=(s:string)=>new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});
const day=(s:string)=>new Date(s).toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'});
const money=(s:string|number)=>Number(s).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:6});
const num=(v:number)=>v.toLocaleString('zh-CN');
const status=(s:string)=>({superseded:'已被覆盖',pending:'排队中',running:'生成中',publishing:'导出中',complete:'已生成',failed:'失败',cancelled:'已取消',no_data:'无消费，已跳过'}[s]||s);
const category=(j:BillingJob)=>{if(j.bill_period)return j.bill_period;const a=new Date(j.range_from!),b=new Date(j.range_to!);const midnight=(v:Date)=>v.toLocaleTimeString('en-GB',{timeZone:'Asia/Shanghai'})==='00:00:00';if(midnight(a)&&midnight(b)&&b.getTime()-a.getTime()===86400000)return'daily';if(midnight(a)&&midnight(b)&&day(j.range_from!).endsWith('-01')&&day(j.range_to!).endsWith('-01'))return'monthly';return'temporary';};
const visible=computed(()=>{const seen=new Set<string>();return items.value.filter(v=>v.job.status==='complete'&&category(v.job)===tab.value).filter(v=>{const k=v.job.range_from+'|'+v.job.range_to;if(seen.has(k))return false;seen.add(k);return true;}).sort((a,b)=>b.job.range_from!.localeCompare(a.job.range_from!));});
const groupModels=computed(()=>props.kind==='user'&&tab.value==='daily');
const tableRows=computed(()=>billingWorkspaceRows(visible.value,groupModels.value));
const defaultBillExpanded=ref(true),billExpansion=ref(new Map<string,boolean>());
const expandableBills=computed(()=>tableRows.value.filter(row=>row.children?.length));
const expandedBillKeys=computed(()=>expandableBills.value.filter(row=>billExpansion.value.get(row.key)??defaultBillExpanded.value).map(row=>row.key));
function changeBillExpansion(row:BillingWorkspaceRow,expanded:boolean){billExpansion.value.set(row.key,expanded);}
function expandAllBills(expanded:boolean){defaultBillExpanded.value=expanded;billExpansion.value.clear();}
watch(()=>[filters.site_id,props.kind,selected.value,month.value],()=>expandAllBills(true));
const billRowClass=({row}:{row:BillingWorkspaceRow})=>row.row_kind==='model'?'model-row':'bill-row';
const discountLabel=formatBillingDiscount;
const originalTotal=computed(()=>visible.value.length && visible.value.every(v=>v.before_amount!=='' && v.before_amount!=null)?visible.value.reduce((a,v)=>a+Number(v.before_amount),0):null);
const totals=computed(()=>visible.value.reduce((a,v)=>({requests:a.requests+v.requests,input:a.input+v.input,output:a.output+v.output,cache:a.cache+v.cache_read+v.cache_write,imageInput:a.imageInput+(v.image_input_tokens||0),imageOutput:a.imageOutput+(v.image_output_tokens||0),audioInput:a.audioInput+(v.audio_input_tokens||0),audioOutput:a.audioOutput+(v.audio_output_tokens||0),amount:a.amount+Number(v.amount),empty:a.empty+v.empty_count,emptyAmount:a.emptyAmount+Number(v.empty_amount)}),{requests:0,input:0,output:0,cache:0,imageInput:0,imageOutput:0,audioInput:0,audioOutput:0,amount:0,empty:0,emptyAmount:0}));
const historyItems=ref<Bill[]>([]);
const tasks=computed(()=>siteJobs.value.map(job=>({job})));
async function searchSubjects(keyword=''){const n=++subjectRevision;try{await filters.loadInstances();if(!filters.site_id)return;const c=await dashboard.siteCurrency(filters.site_id);if(n!==subjectRevision)return;siteCurrency.value=currencyLabel(c);const current=subjects.value.find(v=>v.id===selected.value);if(props.kind==='user'){const r=await passthrough.users({site:filters.site_id,keyword,limit:200});if(n!==subjectRevision)return;subjects.value=r.items.map((u:ReadonlyUser)=>({id:u.id,name:u.display_name||u.username,role:u.role}));}else{const r=await dashboard.billingUpstreams(filters.site_id);if(n!==subjectRevision)return;subjects.value=r.items.map(u=>({id:u.id,name:u.name}));}if(current&&!subjects.value.some(v=>v.id===current.id))subjects.value.unshift(current);if(!selected.value)selected.value=subjects.value[0]?.id;}catch(e){if(n===subjectRevision)error.value=String(e);}}
async function load(quiet=false){const n=++revision;if(view.value!=='workspace'||!selected.value||!month.value)return;if(!quiet)loading.value=true;try{const [r,jobs]=await Promise.all([dashboard.billingWorkspace({instance_id:filters.site_id,kind:props.kind+'_statement',subject_id:selected.value,...period.value}),dashboard.billingJobs({instance_id:filters.site_id,kind:props.kind+'_statement',subject_id:selected.value,limit:200})]);if(n===revision){historyItems.value=jobs.items.filter(j=>j.usage_version===3&&j.job_type===props.kind+'_statement'&&(props.kind==='user'?j.user_id:j.upstream_id)===selected.value).map(job=>({job,requests:0,input:0,output:0,cache_read:0,cache_write:0,amount:'0',before_amount:'0',empty_count:0,empty_amount:'0'}));items.value=r.items;if(activeJob.value){activeJob.value=jobs.items.find(j=>j.id===activeJob.value?.id)||activeJob.value;}remaining.value=r.remaining_days;error.value='';}}catch(e){if(n===revision)error.value=String(e);}finally{if(n===revision)loading.value=false;}}
function openGenerate(m:'fill'|'temporary'|'monthly'){if(creationBlocked.value)return;mode.value=m;range.value=['',''];generate.value=true;}
async function submit(){if(!selected.value)return;saving.value=true;try{let outcome='';if(mode.value==='fill'){const result=await dashboard.generateMissingBills({instance_id:filters.site_id,kind:props.kind+'_statement',subject_id:selected.value,from:period.value.from,to:period.value.to});outcome=result.outcome;}else{const from=mode.value==='monthly'?period.value.from:range.value[0],to=mode.value==='monthly'?period.value.to:range.value[1];if(!from||!to||new Date(to)<=new Date(from)){ElMessage.warning('请选择有效的起止时间');return;}await dashboard.createNewStatement({instance_id:filters.site_id,statement_type:props.kind,period:mode.value,...(props.kind==='user'?{user_id:selected.value}:{upstream_id:selected.value}),from,to});}generate.value=false;if(mode.value==='fill'){const messages:Record<string,string>={no_consumption:'所选范围无消费记录，无需生成账单',already_complete:'所选范围账单已齐全，无需重复生成',generating:'账单正在生成，可查看任务进度',failed:'存在生成失败的任务，请查看生成记录',registered:'补齐已登记，等待继续处理'};ElMessage({type:outcome==='failed'?'warning':outcome==='generating'?'success':'info',message:messages[outcome]||messages.registered});}else{ElMessage.success(mode.value==='monthly'?'月账单已生成':'生成任务已提交');}await load();}catch(e){ElMessage.error(billingTaskErrorMessage(e));}finally{saving.value=false;}}
async function viewProgress(job:BillingJob){activeJob.value=job;progress.value=true;try{steps.value=(await dashboard.billingJobSteps(job.id)).items;}catch(e){ElMessage.error(String(e));}}
function download(v:Bill){const daily=category(v.job)==='daily';startBillingFileDownload(`/api/dashboard/billing/statements/result?id=${encodeURIComponent(v.job.id)}&${daily&&props.kind==='upstream'?'export=daily&day='+day(v.job.range_from!):category(v.job)==='temporary'?'download=1':'download=1&export=summary'}`);}

watch(()=>[filters.site_id,props.kind],()=>{revision++;subjectRevision++;generationBusy.value=true;siteJobs.value=[];if(filters.site_id)void checkGenerationBusy();selected.value=undefined;items.value=[];subjects.value=[];siteCurrency.value='';error.value='';view.value='catalog';},{immediate:true});watch([selected,month,view],()=>{revision++;if(view.value==='workspace'){items.value=[];void load();}});poll=setInterval(()=>{if(filters.site_id)void checkGenerationBusy();if(view.value==='workspace')void load(true);if(progress.value&&activeJob.value)void viewProgress(activeJob.value);},5000);onBeforeUnmount(()=>{revision++;subjectRevision++;busyRevision++;clearInterval(poll);});
</script>
<template><AppShell :title="kind==='user'?'新版用户账单':'上游账单'"><template #tools><el-button @click="openHistory">生成记录</el-button><el-button v-if="view==='workspace'" @click="openGenerate('temporary')" :disabled="!selected||creationBlocked">临时账单</el-button><el-button type="primary" @click="batchView?.open()" :disabled="!filters.site_id||creationBlocked">{{creationBlocked?'任务进行中':'生成账单'}}</el-button></template>
<div class="billing-workspace">
<nav class="view-tabs" aria-label="账单查看方式"><button :class="{active:view==='catalog'}" :aria-pressed="view==='catalog'" @click="view='catalog'">已生成账单</button><button :class="{active:view==='workspace'}" :aria-pressed="view==='workspace'" @click="openWorkspace">按{{kind==='user'?'用户':'上游'}}查看 · 日 / 月</button></nav>
<BillingCatalog v-show="view==='catalog'" ref="catalogView" :site="filters.site_id" :kind="kind" :active="view==='catalog'" @open="openCatalogBill" @download="downloadCatalogBill"/>
<div v-show="view==='workspace'" class="workspace-context"><div><b>{{subjects.find(u=>u.id===selected)?.name||'选择'+(kind==='user'?'用户':'上游')}}</b><small v-if="selected">#{{selected}} · {{month}}</small></div><el-button link type="primary" @click="view='catalog'">返回账单总览 →</el-button></div>
<div v-show="view==='workspace'" class="filters"><el-select v-model="selected" filterable :remote="kind==='user'" :remote-method="searchSubjects" @visible-change="onSubjectDropdown" :placeholder="kind==='user'?'选择用户':'选择上游'" style="width:260px"><el-option v-for="u in subjects" :key="u.id" :value="u.id" :label="`${u.name} · #${u.id}`"/></el-select><el-date-picker v-model="month" type="month" value-format="YYYY-MM" :clearable="false" style="width:145px"/><el-radio-group v-model="tab"><el-radio-button value="daily">日账单</el-radio-button><el-radio-button value="monthly">月账单</el-radio-button><el-radio-button value="temporary">临时账单</el-radio-button></el-radio-group><el-button link @click="sample=true">日账单样例</el-button></div>
<BillingGenerationHistory :kind="kind+'_statement'" ref="historyView" :site="filters.site_id" :subjects="subjects"/>
<BillingGenerationBatch :kind="kind+'_statement'" ref="batchView" :site="filters.site_id" :month="view==='catalog'?(catalogView?.month||month):month" :selected="selected" :subjects="subjects" :busy="generationBusy" @submitted="onGenerated"/>
<button v-if="tasks.length&&!batchView?.hasBatch" class="task-bar" @click="tasks.length?viewProgress(tasks[0].job):openHistory()"><span class="pulse"/>{{tasks.length}} 个生成任务<span v-if="tasks.length"> · {{status(tasks[0].job.status)}}</span><el-progress v-if="tasks.length" :percentage="Math.round(tasks[0].job.completed_steps/Math.max(1,tasks[0].job.total_steps)*100)" :stroke-width="5"/><span>查看进度 →</span></button>
<el-alert v-if="error&&view==='workspace'" type="error" :title="error" :closable="false"/>
<div v-show="view==='workspace'" class="metrics"><article><small>请求总数</small><strong>{{num(totals.requests)}}<em>次</em></strong></article><article><small>普通输入 / 普通输出 / 缓存</small><strong class="usage">{{num(totals.input)}} / {{num(totals.output)}} / {{num(totals.cache)}}</strong><small class="sub">图像输入 / 输出 {{num(totals.imageInput)}} / {{num(totals.imageOutput)}} · 音频输入 / 输出 {{num(totals.audioInput)}} / {{num(totals.audioOutput)}}</small></article><article><small>{{kind==='user'?'账单金额 · '+currency:'上游费用 · '+currency}}</small><strong>{{currency==='多币种'?'—':money(totals.amount)}}</strong><small>原价 {{currency==='多币种'||originalTotal===null?'—':money(originalTotal)}}</small></article><article><small>空输出请求</small><strong>{{num(totals.empty)}}<em>次 · {{money(totals.emptyAmount)}}</em></strong></article></div>
<section v-show="view==='workspace'" v-loading="loading" class="bills"><div v-if="expandableBills.length" class="bill-expansion-actions"><el-button size="small" :disabled="expandedBillKeys.length===expandableBills.length" @click="expandAllBills(true)">全部展开</el-button><el-button size="small" :disabled="!expandedBillKeys.length" @click="expandAllBills(false)">全部收起</el-button></div><el-table :data="tableRows" row-key="key" :expand-row-keys="expandedBillKeys" @expand-change="changeBillExpansion" :row-class-name="billRowClass" size="small" empty-text="暂无账单">
<el-table-column :label="groupModels?'账单日期 / 模型':tab==='daily'?'账单日期':'账单区间'" :min-width="tab==='temporary'?270:tab==='monthly'?290:groupModels?240:155" :show-overflow-tooltip="tab!=='monthly'">
 <template #default="s"><span v-if="s.row.row_kind==='model'" class="model-name">{{s.row.model_name||'未记录模型'}}</span><el-tooltip v-else-if="tab==='monthly'" :content="coverageLabel(s.row.job.monthly_coverage)+'；'+coverageTooltip(s.row.job.monthly_coverage)" placement="top"><div class="monthly-coverage"><b>{{coverageLabel(s.row.job.monthly_coverage)}}</b><small class="sub">{{coverageStatus(s.row.job.monthly_coverage)}}</small></div></el-tooltip><template v-else><b>{{tab==='daily'?day(s.row.job.range_from):local(s.row.job.range_from)+' — '+local(s.row.job.range_to)}}</b><small v-if="groupModels" class="sub bill-model-count">当日合计 · {{s.row.models?.length?s.row.models.length+' 个模型':'暂无模型汇总'}}</small></template></template>
</el-table-column><el-table-column label="请求数" min-width="95" align="right"><template #default="s">{{num(s.row.requests)}}</template></el-table-column><el-table-column label="普通输入 / 输出" min-width="170" align="right"><template #default="s">{{num(s.row.input)}} / {{num(s.row.output)}}</template></el-table-column><el-table-column label="缓存读 / 写" min-width="155" align="right"><template #default="s">{{num(s.row.cache_read)}} / {{num(s.row.cache_write)}}</template></el-table-column><el-table-column label="图像输入 / 输出" min-width="145" align="right"><template #default="s">{{num(s.row.image_input_tokens||0)}} / {{num(s.row.image_output_tokens||0)}}</template></el-table-column><el-table-column label="音频输入 / 输出" min-width="145" align="right"><template #default="s">{{num(s.row.audio_input_tokens||0)}} / {{num(s.row.audio_output_tokens||0)}}</template></el-table-column><el-table-column :label="(kind==='user'?'用户应付':'上游应付')+' · '+currency" header-align="center"><el-table-column label="原价金额" min-width="135" align="right"><template #default="s">{{s.row.before_amount===''||s.row.before_amount==null?'—':money(s.row.before_amount)}}</template></el-table-column><el-table-column label="折扣" width="100" align="center"><template #default="s">{{discountLabel(s.row.discount)}}</template></el-table-column><el-table-column label="折后金额" min-width="120" align="right"><template #default="s"><b>{{money(s.row.amount)}} {{currencyLabel(s.row.currency)}}</b></template></el-table-column></el-table-column><el-table-column label="空输出" width="110"><template #default="s"><span>{{s.row.empty_count}} 次</span><small class="sub">{{money(s.row.empty_amount)}}</small></template></el-table-column><el-table-column label="操作" :width="tab==='monthly'||kind==='user'&&tab==='daily'?210:110"><template #default="s"><template v-if="kind==='user'&&tab==='daily'"><el-button v-if="s.row.row_kind!=='model'||s.row.model_name" link type="primary" @click="detailView?.open(s.row.job,false,s.row.model_name||'')">查看明细</el-button><el-button v-if="s.row.row_kind!=='model'" link type="primary" @click="detailView?.open(s.row.job,true)">下载日明细</el-button></template><template v-else><el-button v-if="tab==='monthly'" link type="primary" @click="monthlyView?.open(s.row.job,subjects.find(u=>u.id===selected)?.name||'')">查看账单</el-button><el-button link type="primary" @click="download(s.row)">下载账单</el-button></template></template></el-table-column></el-table></section></div>
<el-dialog v-model="generate" :title="mode==='fill'?month+' 生成账单':mode==='monthly'?'生成月账单':'临时账单'" width="min(560px,95vw)"><el-form label-position="top"><el-form-item :label="kind==='user'?'用户':'上游'">{{subjects.find(u=>u.id===selected)?.name}} #{{selected}}</el-form-item><el-form-item v-if="mode==='fill'" label="账单月份"><b>{{month}}</b></el-form-item><el-form-item v-else-if="mode==='temporary'" label="账单时间区间"><el-date-picker v-model="range" type="datetimerange" format="YYYY-MM-DD HH:mm" value-format="YYYY-MM-DDTHH:mm:ssZ" start-placeholder="开始时间" end-placeholder="结束时间"/></el-form-item><el-form-item v-else label="账单月份">{{month}}</el-form-item></el-form><template #footer><el-button @click="generate=false">取消</el-button><el-button type="primary" :loading="saving" @click="submit">开始生成</el-button></template></el-dialog>
<el-dialog v-model="history" title="历史生成记录 · 最近 200 条" width="min(950px,96vw)"><el-table :data="historyItems" size="small"><el-table-column label="提交时间" min-width="170"><template #default="s">{{local(s.row.job.created_at)}}</template></el-table-column><el-table-column label="账单区间" min-width="270"><template #default="s">{{local(s.row.job.range_from)}} — {{local(s.row.job.range_to)}}</template></el-table-column><el-table-column label="状态" width="95"><template #default="s">{{status(s.row.job.status)}}</template></el-table-column><el-table-column label="进度" width="120"><template #default="s"><span v-if="category(s.row.job)==='monthly'&&s.row.job.status==='complete'&&s.row.job.total_steps===0">已汇总</span><el-button v-else link @click="viewProgress(s.row.job)">{{s.row.job.completed_steps}} / {{s.row.job.total_steps}}</el-button></template></el-table-column></el-table></el-dialog>
<el-dialog v-model="progress" title="生成进度" width="min(760px,95vw)"><el-alert v-if="activeJob?.error_message" :title="activeJob.error_message" type="error" :closable="false"/><el-table :data="steps" size="small"><el-table-column label="时间段" min-width="270"><template #default="s">{{local(s.row.range_from)}} — {{local(s.row.range_to)}}</template></el-table-column><el-table-column label="状态" width="110"><template #default="s">{{status(s.row.status)}}</template></el-table-column><el-table-column prop="processed_rows" label="已处理请求" width="130"/></el-table></el-dialog>
<el-dialog v-model="sample" title="日账单明细样例" width="min(1120px,96vw)"><el-table :data="[{time:'2026-09-28 10:15:02',request:'req_demo_001',model:'模型 A',token:'生产令牌',token_id:1001,image_input_tokens:512,image_output_tokens:0,audio_input_tokens:0,audio_output_tokens:0,input:1200,output:360,cache:800,write:0,before_amount:'0.016000',discount:'0.8',amount:'0.012800'},{time:'2026-09-28 10:15:18',request:'req_demo_002',model:'模型 B',token:'测试令牌',token_id:1002,image_input_tokens:0,image_output_tokens:0,audio_input_tokens:0,audio_output_tokens:0,input:860,output:0,cache:0,write:0,before_amount:'0.003440',discount:'1',amount:'0.003440'}]" size="small"><el-table-column prop="time" label="时间" width="170"/><el-table-column prop="request" label="请求 ID" width="145"/><el-table-column prop="model" label="模型"/><el-table-column prop="token" label="令牌"/><el-table-column prop="token_id" label="令牌 ID"/><el-table-column prop="input" label="普通输入 Token"/><el-table-column prop="output" label="普通输出 Token"/><el-table-column prop="cache" label="缓存读取"/><el-table-column prop="write" label="缓存写入"/><el-table-column prop="image_input_tokens" label="图像输入"/><el-table-column prop="image_output_tokens" label="图像输出"/><el-table-column prop="audio_input_tokens" label="音频输入"/><el-table-column prop="audio_output_tokens" label="音频输出"/><el-table-column prop="before_amount" label="原价金额" width="110"/><el-table-column label="折扣" width="90"><template #default="s">{{discountLabel(s.row.discount)}}</template></el-table-column><el-table-column prop="amount" :label="'折后金额 '+currency" width="110"/></el-table></el-dialog>
<BillingMonthlyPreview :key="filters.site_id+kind" ref="monthlyView"/><BillingDailyDetails v-if="kind==='user'" :key="filters.site_id" ref="detailView"/></AppShell></template>
<style scoped>
.view-tabs{display:flex;gap:26px;border-bottom:1px solid var(--el-border-color-light);margin-bottom:6px}.view-tabs button{background:transparent;border:0;border-bottom:2px solid transparent;padding:11px 0 14px;color:var(--el-text-color-secondary);font:inherit;font-size:14px;cursor:pointer}.view-tabs button.active{color:var(--el-color-primary);border-bottom-color:var(--el-color-primary)}.workspace-context{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 18px;background:var(--el-bg-color);border:1px solid var(--el-border-color-light);border-radius:9px}.workspace-context b{font-weight:500}.workspace-context small{display:block;font-size:12px;color:var(--el-text-color-secondary);margin-top:4px}
.monthly-coverage b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.bill-expansion-actions{display:flex;justify-content:flex-end;padding:8px 0}.bills :deep(.bill-row){--el-table-tr-bg-color:var(--el-fill-color-light)}.model-name{font-weight:500}.bill-model-count{margin-left:23px}.billing-workspace{display:grid;gap:12px;min-width:0;max-width:100%}.filters{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.metrics{display:grid;grid-template-columns:1fr 2fr 1fr 1.2fr;gap:10px}.metrics article,.bills{min-width:0;background:var(--el-bg-color);border:1px solid var(--el-border-color-light);border-radius:8px;padding:15px 17px}.metrics small{color:var(--el-text-color-secondary);font-size:12px}.metrics strong{display:block;font-size:22px;font-weight:500;margin-top:9px;font-variant-numeric:tabular-nums}.metrics .usage{font-size:18px;margin-top:14px}.metrics em{font-size:12px;font-style:normal;font-weight:400;margin-left:8px;color:var(--el-text-color-secondary)}.bills{padding:5px 16px 12px;min-width:0;max-width:100%;overflow:hidden}.sub{display:block;color:var(--el-text-color-secondary);font-size:11px}.task-bar{display:flex;align-items:center;gap:12px;border:1px solid var(--el-color-primary-light-7);background:var(--el-color-primary-light-9);color:var(--el-color-primary);padding:10px 14px;border-radius:7px;cursor:pointer;text-align:left}.task-bar .el-progress{flex:1;max-width:300px}.task-bar>span:last-child{margin-left:auto}.pulse{width:7px;height:7px;border-radius:50%;background:currentColor}@media(max-width:1000px){.metrics{grid-template-columns:1fr 1fr}}@media(max-width:600px){.metrics{grid-template-columns:1fr}.task-bar{flex-wrap:wrap}}</style>
