<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { ElMessage } from "element-plus";
import { siteOf, type BillingChannelSummary } from "@ct/shared";
import { dashboard } from "../api";
import AppShell from "../components/AppShell.vue";
import AsyncPanel from "../components/AsyncPanel.vue";
import ListPager from "../components/ListPager.vue";
import { useAsyncData } from "../composables/useAsyncData";
import { useFiltersStore } from "../stores/filters";
import { usePrefsStore } from "../stores/prefs";

const filters=useFiltersStore(),prefs=usePrefsStore();const month=ref(new Date().toISOString().slice(0,7)),generating=ref(false),progress=ref(0),page=ref(1),pageSize=ref(20);void prefs.load();
const state=useAsyncData(async()=>{await filters.loadInstances();if(!filters.site_id)return;const ids=filters.instances.filter(v=>v.enabled&&siteOf(v)===filters.site_id).map(v=>v.instance_id);const[bill,snapshots]=await Promise.all([dashboard.billingChannels({instance_id:filters.site_id,month:month.value}),Promise.all(ids.map(instance_id=>dashboard.channelSnapshots({instance_id,latest_only:true,limit:500})))]);const byID=new Map<number,BillingChannelSummary>((bill.items||[]).map(v=>[v.channel_id,v]));for(const channel of snapshots.flatMap(v=>v.items)){if(!byID.has(channel.channel_id))byID.set(channel.channel_id,{channel_id:channel.channel_id,channel_name:channel.channel_name,request_count:0,prompt_tokens:0,completion_tokens:0,cache_tokens:0,abnormal_rows:0,quota:0,amount:"0.000000",discount:"1",discounted_amount:"0.000000",unpriced_models:[]})}return{...bill,items:[...byID.values()].sort((a,b)=>Number(b.amount)-Number(a.amount)||a.channel_id-b.channel_id)}});
const items=computed(()=>state.data.value?.items||[]),pagedItems=computed(()=>items.value.slice((page.value-1)*pageSize.value,page.value*pageSize.value)),currency=computed(()=>prefs.currencySymbol||"$");const money=(v:string)=>`${currency.value}${Number(v||0).toFixed(4)}`;const date=(v:Date)=>`${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,"0")}-${String(v.getDate()).padStart(2,"0")}`;function range(){const start=new Date(`${month.value}-01T00:00:00`),end=new Date(start.getFullYear(),start.getMonth()+1,0),now=new Date();return{start,through:end<now?end:now}}
async function generate(){if(generating.value||!filters.site_id)return;const{start,through}=range();if(start>through){ElMessage.warning("不能生成未来月份账单");return}generating.value=true;progress.value=0;try{const result=await dashboard.generateBilling({instance_id:filters.site_id,from:date(start),to:date(through)});let job=result.job;ElMessage.success(result.reused?"已存在相同账期任务，正在复用结果":"渠道账单补算任务已创建");while(job.status==="pending"||job.status==="running"){progress.value=job.total_steps?Math.round(job.completed_steps*100/job.total_steps):0;await new Promise(r=>setTimeout(r,1500));job=await dashboard.billingJob(job.id)}if(job.status==="failed")throw new Error(job.error_message||"渠道账单补算失败");progress.value=100;await state.reload();ElMessage.success(result.reused?"该账期账单已生成":"渠道账单补算完成")}finally{generating.value=false}}
async function save(row:BillingChannelSummary,value:string){const n=Number(value);if(!Number.isFinite(n)||n<0||n>1){ElMessage.warning("折扣必须在 0 到 1 之间");return}await dashboard.saveBillingChannelDiscount({instance_id:filters.site_id,channel_id:row.channel_id,discount:String(n)});row.discount=String(n);row.discounted_amount=(Number(row.amount)*n).toFixed(6);ElMessage.success("渠道折扣已保存")}
function anomaly(row:BillingChannelSummary){const{start,through}=range();return`/api/dashboard/billing/anomalies?instance_id=${encodeURIComponent(filters.site_id)}&channel_id=${row.channel_id}&from=${date(start)}&to=${date(through)}&format=csv&limit=5000`}
watch([month,()=>filters.site_id],()=>{page.value=1;void state.reload()});watch(pageSize,()=>{page.value=1});void state.reload();
</script>
<template><AppShell title="渠道账单"><template #tools><el-date-picker v-model="month" type="month" value-format="YYYY-MM" format="YYYY-MM" :clearable="false"/><span v-if="generating" class="progress">后台补算 {{progress}}%</span><el-button type="primary" :loading="generating" @click="generate">补算渠道账单</el-button></template><AsyncPanel :loading="state.loading.value||generating" :error="state.error.value" :empty="!items.length" @retry="state.reload"><el-table :data="pagedItems"><el-table-column prop="channel_name" label="渠道" min-width="160"><template #default="s"><b>{{s.row.channel_name||`渠道 ${s.row.channel_id}`}}</b><small class="sub">ID {{s.row.channel_id}}</small></template></el-table-column><el-table-column prop="request_count" label="请求数"/><el-table-column prop="prompt_tokens" label="输入 Token" min-width="120"/><el-table-column prop="completion_tokens" label="输出 Token" min-width="120"/><el-table-column prop="cache_tokens" label="缓存 Token" min-width="120"/><el-table-column label="账单原价"><template #default="s">{{money(s.row.amount)}}</template></el-table-column><el-table-column label="折扣" width="130"><template #default="s"><el-input-number :model-value="Number(s.row.discount)" :min="0" :max="1" :step="0.01" :precision="2" size="small" @change="save(s.row,String($event))"/></template></el-table-column><el-table-column label="折扣总金额"><template #default="s"><b>{{money(s.row.discounted_amount)}}</b></template></el-table-column><el-table-column label="操作" width="130"><template #default="s"><el-button link type="primary" tag="a" :href="anomaly(s.row)">异常订单</el-button></template></el-table-column></el-table><ListPager v-model:page="page" v-model:page-size="pageSize" :item-count="pagedItems.length" :total="items.length"/></AsyncPanel></AppShell></template>
<style scoped>:deep(.el-table){height:calc(100vh - 178px)!important;min-height:320px}.sub{display:block;color:var(--el-text-color-secondary);margin-top:3px}.progress{color:var(--el-color-primary);font-variant-numeric:tabular-nums}@media(max-height:700px){:deep(.el-table){height:calc(100vh - 168px)!important;min-height:240px}}</style>
