<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { CircleCheck, CircleClose, DataLine, Monitor, Stopwatch, TrendCharts } from '@element-plus/icons-vue'
import * as echarts from 'echarts/core'
import { LineChart } from 'echarts/charts'
import { GridComponent, LegendComponent, TooltipComponent } from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import type { AlertItem, MetricItem, Overview } from '@ct/shared'
import { dashboard } from '../api'
import { useAutoRefresh } from '../composables/useAutoRefresh'
import { useFiltersStore } from '../stores/filters'
import AppShell from '../components/AppShell.vue'
import { formatNumber, formatPercent, formatSeconds } from '../utils/format'
echarts.use([LineChart, GridComponent, LegendComponent, TooltipComponent, CanvasRenderer])
const filters = useFiltersStore(); const loading = ref(false); const error = ref(''); const overview = ref<Overview | null>(null); const alerts = ref<AlertItem[]>([]); const history = ref<MetricItem[]>([]); const lastUpdated = ref<Date | null>(null); const chartEl = ref<HTMLDivElement>(); let chart: echarts.ECharts | undefined
const cards = computed(() => { const m=overview.value?.recent_1m; const runtime=overview.value?.runtime; const error=m?.error_rate||0; const success=m?.success_rate||0; return [{label:'成功率',value:formatPercent(m?.success_rate),icon:CircleCheck,tone:success<.95?'danger':success<.99?'warning':'success'},{label:'请求数',value:formatNumber(m?.request_count),icon:TrendCharts,tone:''},{label:'TPM',value:formatNumber(m?.tpm),icon:DataLine,tone:''},{label:'错误率',value:formatPercent(m?.error_rate),icon:CircleClose,tone:error>.05?'danger':error>.01?'warning':'success'},{label:'平均耗时',value:formatSeconds(m?.avg_use_time),icon:Stopwatch,tone:''},{label:'P95 耗时',value:formatSeconds(m?.p95_use_time),icon:Stopwatch,tone:''},{label:'健康检查',value:`${runtime?.health.up_count??0} 正常 / ${runtime?.health.down_count??0} 异常`,icon:Monitor,tone:(runtime?.health.down_count||0)>0?'danger':'success'},{label:'容器',value:`${runtime?.docker.running_count??0} 运行 / ${runtime?.docker.stopped_count??0} 停止`,icon:Monitor,tone:(runtime?.docker.stopped_count||0)>0?'danger':'success'}] })
async function refresh() { if (document.visibilityState !== 'visible') return; loading.value = true; error.value = ''; const instance_id = filters.instance_id || undefined; try { const [o, latest, active] = await Promise.all([dashboard.overview(instance_id), dashboard.metrics({ instance_id, window: '1m', latest: true, dimension_type: 'instance' }), dashboard.alerts({ instance_id, active_only: true, limit: 5 })]); overview.value = o; alerts.value = active.items.slice(0, 5); const metric = latest.items[0]; history.value = metric ? (await dashboard.metricHistory({ window: '1m', dimension_type: 'instance', dimension_key: metric.dimension_key, hours: 1 })).items : []; lastUpdated.value = new Date(); await nextTick(); renderChart() } catch { error.value = '数据加载失败，请稍后重试' } finally { loading.value = false } }
function renderChart() { if (!chartEl.value) return; chart ??= echarts.init(chartEl.value); chart.setOption({ tooltip: { trigger: 'axis' }, legend: { data: ['请求量', '错误数'] }, grid: { left: 38, right: 20, bottom: 30, top: 45 }, xAxis: { type: 'category', data: history.value.map(x => new Date(x.bucket_time).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })) }, yAxis: { type: 'value', minInterval: 1 }, series: [{ name: '请求量', type: 'line', smooth: true, data: history.value.map(x => x.request_count) }, { name: '错误数', type: 'line', smooth: true, data: history.value.map(x => x.error_count) }] }) }
function resize() { chart?.resize() }
useAutoRefresh(refresh); watch(() => filters.instance_id, () => void refresh()); window.addEventListener('resize', resize); onBeforeUnmount(() => { window.removeEventListener('resize', resize); chart?.dispose() })
</script>
<template><AppShell title="运行总览"><section v-loading="loading"><div class="updated">最后刷新：{{lastUpdated?lastUpdated.toLocaleTimeString():'—'}}</div><el-alert v-if="error" :title="error" type="error" show-icon @close="error=''"/><el-alert v-if="filters.loaded&&!filters.instances.length" class="instance-guide" type="info" :closable="false" show-icon><template #title>尚未创建实例——<router-link to="/instances">前往实例管理创建并部署 Agent</router-link></template></el-alert><div class="kpi-grid"><article v-for="card in cards" :key="card.label" class="kpi kpi-card" :class="`tone-${card.tone}`"><el-icon class="kpi-icon"><component :is="card.icon"/></el-icon><span>{{card.label}}</span><strong>{{card.value}}</strong></article></div><div class="dashboard-grid"><section class="panel chart-panel"><div class="panel-title"><h2>近一小时趋势</h2><span>请求量 / 错误数</span></div><div v-if="history.length" ref="chartEl" class="chart"></div><el-empty v-else description="Agent 上报后将显示近一小时趋势"/></section><section class="panel alerts-panel"><div class="panel-title"><h2>当前告警</h2><span>最多 5 条</span></div><div v-if="alerts.length" class="alert-list"><article v-for="item in alerts" :key="item.id" class="alert-item"><el-tag :type="item.severity==='critical'?'danger':'warning'" size="small">{{item.severity}}</el-tag><div><strong>{{item.display_key||item.title}}</strong><p>{{item.summary}}</p><small>{{item.instance_name}}</small></div></article></div><el-empty v-else description="当前没有活跃告警"/></section></div></section></AppShell></template>
