<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import * as echarts from 'echarts/core'
import { LineChart } from 'echarts/charts'
import { GridComponent, LegendComponent, TooltipComponent } from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import type { AlertItem, MetricItem, Overview } from '@ct/shared'
import { dashboard } from '../api'
import { useAuthStore } from '../stores/auth'
import { useAutoRefresh } from '../composables/useAutoRefresh'
import { useFiltersStore } from '../stores/filters'
import InstanceSelect from '../components/InstanceSelect.vue'
echarts.use([LineChart, GridComponent, LegendComponent, TooltipComponent, CanvasRenderer])
const store = useAuthStore(); const filters = useFiltersStore(); const router = useRouter(); const loading = ref(false); const error = ref(''); const overview = ref<Overview | null>(null); const alerts = ref<AlertItem[]>([]); const history = ref<MetricItem[]>([]); const lastUpdated = ref<Date | null>(null); const chartEl = ref<HTMLDivElement>(); let chart: echarts.ECharts | undefined
const cards = computed(() => { const m = overview.value?.recent_1m; const runtime = overview.value?.runtime; return [{ label: '成功率', value: percent(m?.success_rate) }, { label: '请求数', value: String(m?.request_count ?? 0) }, { label: 'TPM', value: String(m?.tpm ?? 0) }, { label: '错误率', value: percent(m?.error_rate) }, { label: '平均耗时', value: seconds(m?.avg_use_time) }, { label: 'P95 耗时', value: seconds(m?.p95_use_time) }, { label: '健康检查', value: `${runtime?.health.up_count ?? 0} 正常 / ${runtime?.health.down_count ?? 0} 异常` }, { label: '容器', value: `${runtime?.docker.running_count ?? 0} 运行 / ${runtime?.docker.stopped_count ?? 0} 停止` }] })
function percent(value?: number | null) { return value == null ? '—' : `${(value * 100).toFixed(1)}%` } function seconds(value?: number | null) { return value == null ? '—' : `${value.toFixed(2)}s` }
async function refresh() { if (document.visibilityState !== 'visible') return; loading.value = true; error.value = ''; const instance_id = filters.instance_id || undefined; try { const [o, latest, active] = await Promise.all([dashboard.overview(instance_id), dashboard.metrics({ instance_id, window: '1m', latest: true, dimension_type: 'instance' }), dashboard.alerts({ instance_id, active_only: true, limit: 5 })]); overview.value = o; alerts.value = active.items.slice(0, 5); const metric = latest.items[0]; history.value = metric ? (await dashboard.metricHistory({ window: '1m', dimension_type: 'instance', dimension_key: metric.dimension_key, hours: 1 })).items : []; lastUpdated.value = new Date(); await nextTick(); renderChart() } catch { error.value = '数据加载失败，请稍后重试' } finally { loading.value = false } }
function renderChart() { if (!chartEl.value) return; chart ??= echarts.init(chartEl.value); chart.setOption({ tooltip: { trigger: 'axis' }, legend: { data: ['请求量', '错误数'] }, grid: { left: 38, right: 20, bottom: 30, top: 45 }, xAxis: { type: 'category', data: history.value.map(x => new Date(x.bucket_time).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })) }, yAxis: { type: 'value', minInterval: 1 }, series: [{ name: '请求量', type: 'line', smooth: true, data: history.value.map(x => x.request_count) }, { name: '错误数', type: 'line', smooth: true, data: history.value.map(x => x.error_count) }] }) }
async function logout() { await store.logout(); await router.replace('/login') } function resize() { chart?.resize() }
useAutoRefresh(refresh); watch(() => filters.instance_id, () => void refresh()); window.addEventListener('resize', resize); onBeforeUnmount(() => { window.removeEventListener('resize', resize); chart?.dispose() })
</script>
<template><div class="shell"><aside class="sidebar"><div class="logo"><span>CT</span> Control Tower</div><nav><div class="nav-group">监控</div><router-link to="/">总览</router-link><router-link to="/customers">客户监控</router-link><router-link to="/channels">渠道监控</router-link><router-link to="/models">模型监控</router-link><div class="nav-group">分析</div><router-link to="/samples">样本分析</router-link><router-link to="/usage">用量统计</router-link><div class="nav-group">系统</div><router-link to="/runtime">系统状态</router-link></nav></aside><main class="workspace"><header class="topbar"><div><h1>运行总览</h1><span class="updated">最后刷新：{{ lastUpdated ? lastUpdated.toLocaleTimeString() : '—' }}</span></div><div class="user"><InstanceSelect/><span>{{ store.user?.username }}</span><el-button text @click="logout">退出</el-button></div></header><section v-loading="loading" class="content"><el-alert v-if="error" :title="error" type="error" show-icon @close="error = ''" /><div class="kpi-grid"><article v-for="card in cards" :key="card.label" class="kpi"><span>{{ card.label }}</span><strong>{{ card.value }}</strong></article></div><div class="dashboard-grid"><section class="panel chart-panel"><div class="panel-title"><h2>近一小时趋势</h2><span>请求量 / 错误数</span></div><div v-if="history.length" ref="chartEl" class="chart"></div><el-empty v-else description="暂无实例指标数据" /></section><section class="panel alerts-panel"><div class="panel-title"><h2>当前告警</h2><span>最多 5 条</span></div><div v-if="alerts.length" class="alert-list"><article v-for="item in alerts" :key="item.id" class="alert-item"><el-tag :type="item.severity === 'critical' ? 'danger' : 'warning'" size="small">{{ item.severity }}</el-tag><div><strong>{{ item.title }}</strong><p>{{ item.summary }}</p></div></article></div><el-empty v-else description="当前无告警" /></section></div></section></main></div></template>
